name: agconnect_apm
description: App Performance Management (APM) of HUAWEI AppGallery Connect provides minute-level app performance monitoring capabilities.
homepage: https://developer.huawei.com/consumer/en/agconnect/

version: 1.4.0+300

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.9"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.agconnectapm
        pluginClass: AGConnectAPMPlugin
      ios:
        pluginClass: AGConnectAPMPlugin
