// Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.

abstract class MethodConstants {
  static const String ENABLE_COLLECTION = 'ENABLE_COLLECTION';
  static const String ENABLE_ANR_MONITOR = 'ENABLE_ANR_MONITOR';
  static const String CREATE_CUSTOM_TRACE = 'CREATE_CUSTOM_TRACE';
  static const String CREATE_NETWORK_MEASURE = 'CREATE_NETWORK_MEASURE';
  static const String SET_USER_IDENTIFIER = 'SET_USER_IDENTIFIER';

  // Inner methods of custom trace object
  static const String CUSTOM_TRACE_INNER = "CUSTOM_TRACE_INNER";
  static const String CUSTOM_TRACE_START = "CUSTOM_TRACE_START";
  static const String CUSTOM_TRACE_STOP = "CUSTOM_TRACE_STOP";
  static const String CUSTOM_TRACE_PUT_PROPERTY = "CUSTOM_TRACE_PUT_PROPERTY";
  static const String CUSTOM_TRACE_REMOVE_PROPERTY = "CUSTOM_TRACE_REMOVE_PROPERTY";
  static const String CUSTOM_TRACE_GET_PROPERTY = "CUSTOM_TRACE_GET_PROPERTY";
  static const String CUSTOM_TRACE_GET_PROPERTIES = "CUSTOM_TRACE_GET_PROPERTIES";
  static const String CUSTOM_TRACE_PUT_MEASURE = "CUSTOM_TRACE_PUT_MEASURE";
  static const String CUSTOM_TRACE_GET_MEASURE = "CUSTOM_TRACE_GET_MEASURE";
  static const String CUSTOM_TRACE_INCREMENT_MEASURE = "CUSTOM_TRACE_INCREMENT_MEASURE";

  // Inner methods of network measure object
  static const String NETWORK_MEASURE_INNER = "NETWORK_MEASURE_INNER";
  static const String NETWORK_MEASURE_START = "NETWORK_MEASURE_START";
  static const String NETWORK_MEASURE_STOP = "NETWORK_MEASURE_STOP";
  static const String NETWORK_MEASURE_PUT_PROPERTY = "NETWORK_MEASURE_PUT_PROPERTY";
  static const String NETWORK_MEASURE_REMOVE_PROPERTY = "NETWORK_MEASURE_REMOVE_PROPERTY";
  static const String NETWORK_MEASURE_GET_PROPERTY = "NETWORK_MEASURE_GET_PROPERTY";
  static const String NETWORK_MEASURE_GET_PROPERTIES = "NETWORK_MEASURE_GET_PROPERTIES";
  static const String NETWORK_MEASURE_SET_STATUS_CODE = "NETWORK_MEASURE_SET_STATUS_CODE";
  static const String NETWORK_MEASURE_SET_CONTENT_TYPE = "NETWORK_MEASURE_SET_CONTENT_TYPE";
  static const String NETWORK_MEASURE_SET_BYTES_SEND = "NETWORK_MEASURE_SET_BYTES_SEND";
  static const String NETWORK_MEASURE_SET_BYTES_RECEIVED = "NETWORK_MEASURE_SET_BYTES_RECEIVED";
}
